name: Install Vagrant

on:
  push:
    branches:
      - main

jobs:
  install-vagrant:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vagrant
        run: |
          sudo apt-get update
          sudo apt-get install -y vagrant
